import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { supabaseServer } from '@/lib/supabase/server'
import AppShell from '@/components/app-shell'
import { Analytics } from '@vercel/analytics/next'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const supabase = await supabaseServer()
  const { data } = await supabase.auth.getUser()
  const user = data.user

  let showAdmin = false
  if (user) {
    const { data: isAdmin } = await supabase.rpc('is_admin')
    showAdmin = !!isAdmin
  }

  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppShell showAdmin={showAdmin}>{children}</AppShell>
        <Analytics />
      </body>
    </html>
  )
}
